<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Wireless Noise-Cancelling Headphones',
                'slug' => 'wireless-noise-cancelling-headphones',
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 299.99,
                'description' => 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and superior sound quality. Perfect for music lovers and professionals.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'is_new' => false,
                'is_sale' => true,
                'quantity' => 45,
                'sold' => 128,
                'views' => 2450,
                'rating' => 4,
                'rating_count' => 89,
                'order' => 1,
            ],
            [
                'name' => 'Stainless Steel Smart Watch',
                'slug' => 'stainless-steel-smart-watch',
                'image' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 189.99,
                'description' => 'Elegant stainless steel smartwatch with health tracking, notifications, and up to 14 days battery life. Water resistant and stylish for daily wear.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => false,
                'is_new' => true,
                'is_sale' => false,
                'quantity' => 67,
                'sold' => 203,
                'views' => 1840,
                'rating' => 5,
                'rating_count' => 124,
                'order' => 2,
            ],
            [
                'name' => 'Organic Cotton T-Shirt',
                'slug' => 'organic-cotton-t-shirt',
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 24.99,
                'description' => 'Ultra-soft organic cotton t-shirt available in multiple colors. Breathable, durable, and perfect for everyday casual wear.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => true,
                'is_new' => false,
                'is_sale' => true,
                'quantity' => 120,
                'sold' => 450,
                'views' => 3200,
                'rating' => 4,
                'rating_count' => 67,
                'order' => 3,
            ],
            [
                'name' => 'Espresso Coffee Machine',
                'slug' => 'espresso-coffee-machine',
                'image' => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 349.99,
                'description' => 'Professional-grade espresso machine with milk frother and programmable settings. Brew barista-quality coffee at home.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'is_new' => false,
                'is_sale' => false,
                'quantity' => 28,
                'sold' => 87,
                'views' => 1560,
                'rating' => 5,
                'rating_count' => 45,
                'order' => 4,
            ],
            [
                'name' => 'Minimalist Leather Backpack',
                'slug' => 'minimalist-leather-backpack',
                'image' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 89.99,
                'description' => 'Premium full-grain leather backpack with multiple compartments. Durable, stylish, and perfect for work or travel.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => false,
                'is_new' => true,
                'is_sale' => true,
                'quantity' => 55,
                'sold' => 132,
                'views' => 980,
                'rating' => 4,
                'rating_count' => 78,
                'order' => 5,
            ],
            [
                'name' => '4K Ultra HD Smart TV 55 inch',
                'slug' => '4k-ultra-hd-smart-tv-55-inch',
                'image' => 'https://images.unsplash.com/photo-1593784991095-a205069470b6?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 649.99,
                'description' => 'Crystal clear 4K UHD display with smart features, HDR support, and built-in streaming apps.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'is_new' => false,
                'is_sale' => false,
                'quantity' => 34,
                'sold' => 65,
                'views' => 4120,
                'rating' => 5,
                'rating_count' => 92,
                'order' => 6,
            ],
            [
                'name' => 'Yoga Mat Premium Non-Slip',
                'slug' => 'yoga-mat-premium-non-slip',
                'image' => 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 34.99,
                'description' => 'Eco-friendly 6mm thick yoga mat with excellent grip and cushioning for all yoga styles.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => false,
                'is_new' => false,
                'is_sale' => true,
                'quantity' => 89,
                'sold' => 312,
                'views' => 1870,
                'rating' => 4,
                'rating_count' => 156,
                'order' => 7,
            ],
            [
                'name' => 'Wireless Gaming Mouse',
                'slug' => 'wireless-gaming-mouse',
                'image' => 'https://images.unsplash.com/photo-1615663248834-9b6e0f2c4c0c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 59.99,
                'description' => 'High-precision wireless gaming mouse with customizable RGB lighting and long battery life.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'is_new' => true,
                'is_sale' => false,
                'quantity' => 76,
                'sold' => 245,
                'views' => 2890,
                'rating' => 5,
                'rating_count' => 134,
                'order' => 8,
            ],
            [
                'name' => 'Ceramic Dinnerware Set 16 Piece',
                'slug' => 'ceramic-dinnerware-set-16-piece',
                'image' => 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 79.99,
                'description' => 'Elegant modern ceramic dinner set for 4 people. Dishwasher and microwave safe.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => false,
                'is_new' => false,
                'is_sale' => true,
                'quantity' => 42,
                'sold' => 98,
                'views' => 760,
                'rating' => 4,
                'rating_count' => 53,
                'order' => 9,
            ],
            [
                'name' => 'Portable Bluetooth Speaker',
                'slug' => 'portable-bluetooth-speaker',
                'image' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 49.99,
                'description' => 'Waterproof portable speaker with powerful bass, 12-hour playtime, and clear sound.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'is_new' => false,
                'is_sale' => false,
                'quantity' => 110,
                'sold' => 387,
                'views' => 5210,
                'rating' => 4,
                'rating_count' => 201,
                'order' => 10,
            ],
            [
                'name' => 'LED Desk Lamp with Wireless Charger',
                'slug' => 'led-desk-lamp-with-wireless-charger',
                'image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 45.99,
                'description' => 'Modern LED desk lamp with touch control, multiple brightness levels, and built-in wireless phone charger.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => false,
                'is_new' => true,
                'is_sale' => true,
                'quantity' => 68,
                'sold' => 156,
                'views' => 1240,
                'rating' => 5,
                'rating_count' => 82,
                'order' => 11,
            ],
            [
                'name' => 'Running Shoes Men/Women',
                'slug' => 'running-shoes-men-women',
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 79.99,
                'description' => 'Lightweight and comfortable running shoes with excellent cushioning and breathable mesh upper.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'is_new' => false,
                'is_sale' => false,
                'quantity' => 95,
                'sold' => 324,
                'views' => 3780,
                'rating' => 4,
                'rating_count' => 167,
                'order' => 12,
            ],
            [
                'name' => 'Stainless Steel Water Bottle 1L',
                'slug' => 'stainless-steel-water-bottle-1l',
                'image' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 19.99,
                'description' => 'Double-wall insulated stainless steel bottle. Keeps drinks cold for 24h and hot for 12h.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => false,
                'is_new' => false,
                'is_sale' => true,
                'quantity' => 150,
                'sold' => 892,
                'views' => 6450,
                'rating' => 5,
                'rating_count' => 245,
                'order' => 13,
            ],
            [
                'name' => 'Wireless Mechanical Keyboard',
                'slug' => 'wireless-mechanical-keyboard',
                'image' => 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80',
                'price' => 129.99,
                'description' => 'RGB backlit wireless mechanical keyboard with hot-swappable switches and long battery life.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'is_new' => true,
                'is_sale' => false,
                'quantity' => 52,
                'sold' => 178,
                'views' => 2890,
                'rating' => 5,
                'rating_count' => 98,
                'order' => 14,
            ],
            [
                'name' => 'Skincare Vitamin C Serum',
                'slug' => 'skincare-vitamin-c-serum',
                'image' => 'https://images.unsplash.com/photo-1556228720-195a672ee8b6?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 29.99,
                'description' => 'Brightening Vitamin C facial serum. Helps reduce dark spots and improve skin glow.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => true,
                'is_new' => false,
                'is_sale' => true,
                'quantity' => 83,
                'sold' => 412,
                'views' => 5210,
                'rating' => 4,
                'rating_count' => 189,
                'order' => 15,
            ],
            [
                'name' => 'Electric Standing Desk',
                'slug' => 'electric-standing-desk',
                'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 399.99,
                'description' => 'Height-adjustable electric standing desk with memory presets, spacious workspace, and modern minimalist design.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'is_new' => true,
                'is_sale' => false,
                'quantity' => 22,
                'sold' => 67,
                'views' => 1850,
                'rating' => 5,
                'rating_count' => 54,
                'order' => 16,
            ],
            [
                'name' => 'Wireless Earbuds with ANC',
                'slug' => 'wireless-earbuds-with-anc',
                'image' => 'https://images.unsplash.com/photo-1610438237134-9c4e4c8f5e9f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 89.99,
                'description' => 'Compact true wireless earbuds featuring active noise cancellation, touch controls, and 28-hour total playtime.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'is_new' => false,
                'is_sale' => true,
                'quantity' => 135,
                'sold' => 428,
                'views' => 6720,
                'rating' => 4,
                'rating_count' => 312,
                'order' => 17,
            ],
            [
                'name' => 'Cashmere Wool Sweater',
                'slug' => 'cashmere-wool-sweater',
                'image' => 'https://images.unsplash.com/photo-1622445275576-721325763afe?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 119.99,
                'description' => 'Luxuriously soft cashmere blend sweater. Timeless design perfect for layering in any season.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => false,
                'is_new' => true,
                'is_sale' => false,
                'quantity' => 48,
                'sold' => 95,
                'views' => 1240,
                'rating' => 5,
                'rating_count' => 73,
                'order' => 18,
            ],
            [
                'name' => 'Robot Vacuum Cleaner',
                'slug' => 'robot-vacuum-cleaner',
                'image' => 'https://images.unsplash.com/photo-1568819313-4e9d4a0a1c2f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 249.99,
                'description' => 'Smart robot vacuum with powerful suction, mopping function, app control, and self-charging capability.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'is_new' => false,
                'is_sale' => true,
                'quantity' => 31,
                'sold' => 142,
                'views' => 3980,
                'rating' => 4,
                'rating_count' => 108,
                'order' => 19,
            ],
            [
                'name' => 'Bamboo Cutting Board Set',
                'slug' => 'bamboo-cutting-board-set',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 34.99,
                'description' => 'Set of 3 premium bamboo cutting boards with juice grooves. Naturally antibacterial and durable.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => false,
                'is_new' => false,
                'is_sale' => true,
                'quantity' => 87,
                'sold' => 265,
                'views' => 980,
                'rating' => 4,
                'rating_count' => 89,
                'order' => 20,
            ],
            [
                'name' => 'Polarized Sunglasses',
                'slug' => 'polarized-sunglasses',
                'image' => 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80',
                'price' => 49.99,
                'description' => 'Stylish UV400 polarized sunglasses with lightweight frame and premium protection for outdoor use.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => true,
                'is_new' => true,
                'is_sale' => false,
                'quantity' => 72,
                'sold' => 198,
                'views' => 2140,
                'rating' => 5,
                'rating_count' => 145,
                'order' => 21,
            ],
            [
                'name' => 'Aromatherapy Essential Oil Diffuser',
                'slug' => 'aromatherapy-essential-oil-diffuser',
                'image' => 'https://images.unsplash.com/photo-1600210492493-094691112ba1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 39.99,
                'description' => 'Ultrasonic cool mist diffuser with 7 color LED lights, auto shut-off, and large capacity tank.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => false,
                'is_new' => false,
                'is_sale' => true,
                'quantity' => 64,
                'sold' => 231,
                'views' => 1670,
                'rating' => 4,
                'rating_count' => 112,
                'order' => 22,
            ],
            [
                'name' => 'Leather Card Holder Wallet',
                'slug' => 'leather-card-holder-wallet',
                'image' => 'https://images.unsplash.com/photo-1627123424574-724758594e93?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 29.99,
                'description' => 'Slim genuine leather RFID blocking card holder wallet with money clip. Minimalist and functional.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => false,
                'is_new' => true,
                'is_sale' => false,
                'quantity' => 105,
                'sold' => 376,
                'views' => 2890,
                'rating' => 5,
                'rating_count' => 167,
                'order' => 23,
            ],
            [
                'name' => 'Resistance Bands Set with Handles',
                'slug' => 'resistance-bands-set-with-handles',
                'image' => 'https://images.unsplash.com/photo-1598632647813-9f6c6e6f7f0e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 24.99,
                'description' => 'Complete set of 5 resistance bands with handles, door anchor, and carrying bag for full body workout.',
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => true,
                'is_new' => false,
                'is_sale' => true,
                'quantity' => 94,
                'sold' => 512,
                'views' => 3450,
                'rating' => 4,
                'rating_count' => 203,
                'order' => 24,
            ],
            [
                'name' => 'Ceramic Non-Stick Cookware Set',
                'slug' => 'ceramic-non-stick-cookware-set',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
                'price' => 129.99,
                'description' => '10-piece premium ceramic non-stick cookware set. PFOA-free, induction compatible, and easy to clean.',
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'is_new' => false,
                'is_sale' => false,
                'quantity' => 38,
                'sold' => 124,
                'views' => 1980,
                'rating' => 5,
                'rating_count' => 87,
                'order' => 25,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('ProductSeeder: 15 realistic products seeded successfully!');
    }
}
